# ============================================================
# LeetCode 389 - Find the Difference
# Difficulty: Easy
# ============================================================
#
# QUESTION:
# You are given two strings s and t. String t is generated by random
# shuffling string s and adding one more letter at a random position.
# Return the letter that was added to t.
#
# Example:
#   Input:  s = "abcd", t = "abcde"   Output: "e"
#   Input:  s = "", t = "y"           Output: "y"
#
# Constraints:
#   - 0 <= s.length <= 1000
#   - t.length == s.length + 1
#   - s and t consist of lowercase English letters.
#
# ============================================================
# THEORY / APPROACH:
# XOR approach: XOR all characters in s and t together.
# Each character in s appears twice (once in s, once in t except for
# the added character). XOR of identical values = 0. The remaining
# value is the added character.
#
# Time Complexity:  O(n)
# Space Complexity: O(1)
# ============================================================

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        result = 0
        for ch in s + t:
            result ^= ord(ch)
        return chr(result)
